version: '3'
services:
  pics_io_backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - .:/usr/src/app

  pics_io_db:
    ports:
      - 27017:27017